name: Build Servo (Windows x64)
on: [push]

env:
  RUSTUP_TOOLCHAIN_FILE: rust-toolchain

jobs:
  build:
    name: Build Servo (Windows x64)
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ahmadmdabit/servo
          submodules: true

      - name: Restore cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          override: true
          components: rustfmt, clippy
          cache: true
          cache-on-failure: true
          cache-bin: true

      - name: Restore Rust build cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # CORRECTED STEP:
      # This step now correctly creates the virtual environment, installs dependencies into it,
      # and adds the venv's Scripts directory to the PATH for subsequent steps.
      - name: Install Python dependencies and add venv to PATH
        shell: pwsh
        run: |
          python -m pip install --upgrade pip virtualenv
          python -m virtualenv .venv
          .venv\Scripts\activate.ps1
          pip install uv
          echo "$env:GITHUB_WORKSPACE\.venv\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Bootstrap
        run: .\mach.bat bootstrap
        shell: pwsh

      - name: Build Servo
        run: .\mach.bat build --dev
        shell: pwsh

      - name: Package Servo
        run: .\mach.bat package --dev
        shell: pwsh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: servo-windows-msvc
          path: |
            target/dev/servo.exe
            target/dev/servo.pdb
            target/dev/resources
            target/dev/*.dll
