# .github/workflows/windows-build.yml
name: Build Servo on Windows x64

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-windows:
    name: Build Servo (Windows x64)
    runs-on: windows-latest

    env:
      RUSTUP_TOOLCHAIN_FILE: rust-toolchain

    steps:
      - name: 🛎️ Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: 📦 Cache Cargo registry & git index
        uses: actions/cache@v3
        id: cargo-cache
        with:
          path:
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: ⚙️ Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          override: true
          components: rustfmt, clippy

      - name: 🐍 Install Python (for mach)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: ✨ Setup Python Virtual Environment
        run: |
          python -m pip install --upgrade pip virtualenv
          python -m virtualenv .venv
        # Add the virtual environment's Scripts directory to PATH for subsequent steps
      - name: 🔧 Add venv to PATH
        run: echo "C:\a\servo\.venv\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding Utf8 -Append
        shell: pwsh # Use PowerShell for this specific step to correctly add to GITHUB_PATH

      - name: ⚡ Bootstrap Servo build system
        # Now mach.bat and python commands will automatically use the venv
        run: .\mach.bat bootstrap

      - name: 🏗️ Build Servo (Release)
        run: .\mach.bat build --release

      - name: 📤 Upload Release Binaries
        uses: actions/upload-artifact@v4
        with:
          name: servo-windows-x64
          path: |
            ./target/x86_64-pc-windows-msvc/release/servo.exe
            ./target/x86_64-pc-windows-msvc/release/components/**

      - name: ✅ Build succeeded
        if: ${{ success() }}
        run: echo "Servo built successfully for Windows x64!"
