# .github/workflows/windows-build.yml
name: Build Servo on Windows x64

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-windows:
    name: Build Servo (Windows x64)
    runs-on: windows-latest   # Microsoft’s hosted Windows VM is x64 by default

    env:
      # Point rustup at the toolchain file shipped with Servo
      RUSTUP_TOOLCHAIN_FILE: rust-toolchain

    steps:
      - name: 🛎️ Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: 📦 Cache Cargo registry & git index
        uses: actions/cache@v3
        id: cargo-cache
        with:
          path: |
            ${{ runner.cache }}/cargo/registry
            ${{ runner.cache }}/cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: ⚙️ Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          # servo’s rust-toolchain pins to a nightly or specific version
          toolchain: ${{ env.RUSTUP_TOOLCHAIN_FILE }}   # picks up version from rust-toolchain
          override: true
          components: rustfmt, clippy                     

      - name: 🐍 Install Python (for mach)
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'    # Servo’s tooling works with 3.x

      - name: ⚡ Bootstrap Servo build system
        # Activate a clean virtualenv & install Servo’s Python bits
        run: |
          python -m pip install --upgrade pip virtualenv
          python -m virtualenv .venv
          .venv\Scripts\activate
          .\mach.bat bootstrap

      - name: 🏗️ Build Servo (Release)
        run: |
          .venv\Scripts\activate
          .\mach.bat build --release
        # If you hit OOM or build stalls, you can pass `-v` for verbose logs.

      - name: 📤 Upload Release Binaries
        uses: actions/upload-artifact@v3
        with:
          name: servo-windows-x64
          path: |
            ./target/x86_64-pc-windows-msvc/release/servo.exe
            ./target/x86_64-pc-windows-msvc/release/components/**

      - name: ✅ Build succeeded
        if: ${{ success() }}
        run: echo "Servo built successfully for Windows x64!"
